### ISSUE TITLE
Getting Error "Command 'SnippetsLab: Show All Snippets' resulted in an error"

### ISSUE THREAD

**Issue by skyrkou** [sisoe24/vscode-snippetslab#1]
I am getting the following error, any ideas?
Command 'SnippetsLab: Show All Snippets' resulted in an error
command 'snippetslab.showAllSnippets' not found

**Comment by sisoe24** [comment]
Hi! Thanks for reaching out!

The only thing I can think of is checking the backup folder to ensure everything is as expected. First, I would verify if backups are activated.

![image](https://github.com/sisoe24/vscode-snippetslab/assets/28490646/8b6e4187-9914-4fe6-a1a1-6ccc92046a9e)

Then, I would check if the location matches the one in vscode:  `~/Library/Containers/com.renfei.SnippetsLab/Data/Library/Application Support/Backups`

And a backup file would look like this 

```
Backups/
└── main 9-9-23, 4-08-42 PM (automatic).snippetslab-backup
    ├── library.json
    ├── main.snippetslablibrary
    └── meta.json
```

Let me know

**Comment by skyrkou** [comment]
Yes the issue was with the path, I had the full path there and I edit it to start with ~/
Thank you, great extension!!
